Realised all errors, bugs are fixed

diff --git a/lab_1/reverse b/lab_1/reverse
--- a/lab_1/reverse
+++ b/lab_1/reverse
@@ -2,11 +2,11 @@
 
 reverse () {
 
-if [[ $# -ne 2 ]]; then echo "More/less arguments"; return -10; fi
-if ! [[ -f "$1" ]]; then echo "File doest't exist"; return -8; fi
-if ! [[ -f "$1" ]]; then echo "Can't read file"; return -9; fi
+if [[ $# -ne 2 ]]; then echo "Too many/Not enough arguments!" >&2; return -10; fi
+if ! [[ -f "$1" ]]; then echo "File doest't exist!" >&2; return -8; fi
+if ! [[ -f "$1" ]]; then echo "Can't read file!" >&2; return -9; fi
 if [[ -f "$2" ]]; then
-  if ! [[ -w "$2" ]]; then echo "Can't write in file"; return -11; fi
+  if ! [[ -w "$2" ]]; then echo "Can't write in file!" >&2; return -11; fi
 fi
 true > "$2"
 echo "Enter W to write in file or Enter A to append in file"
@@ -14,9 +14,7 @@ read tmp
 case $tmp in
   W) tac $1 > $2;;
   A) tac $1 >> $2;;
-  *) echo "Invalid parametr"
-     return -1
-     ;;
+  *) echo "Invalid parametr!" >&2; return -1;;
 esac
 
 }
