New version of reverse

diff --git a/lab_1/reverse b/lab_1/reverse
--- a/lab_1/reverse
+++ b/lab_1/reverse
@@ -7,14 +7,19 @@ if ! [[ -f "$1" ]]; then echo "File doest't exist!" >&2; return -8; fi
 if ! [[ -r "$1" ]]; then echo "Can't read file!" >&2; return -9; fi
 if [[ -f "$2" ]]; then
   if ! [[ -w "$2" ]]; then echo "Can't write in file!" >&2; return -11; fi
+else
+  dir=$(dirname "$2")
+  if ! [[ -d "$dir" ]]; then echo "Directory doesn't exist!" >&2; return -8; fi
+  if ! [[ -w "$dir" ]]; then echo "Can't read directory!" >&2; return -9; fi
 fi
 echo "Enter W to write in file or Enter A to append in file"
 read tmp
-case $tmp in 
-  W | w) 
-    t=$(mktemp)
-    tac "$1" | rev > $t && cat $t > $2
-    rm $t 
+case $tmp in
+  W | w)
+    #t=$(mktemp)
+    tac "$1" | tee "$2" >/dev/null
+    #tac "$1" | rev > $t && cat $t > $2
+    #rm $t
     ;;
   A | a) tac $1 >> $2;;
   *) echo "Invalid parametr!" >&2; return -1;;
