FINALY I DID IT

diff --git a/lab_1/reverse b/lab_1/reverse
--- a/lab_1/reverse
+++ b/lab_1/reverse
@@ -4,7 +4,7 @@ reverse () {
 
 if [[ $# -ne 2 ]]; then echo "Too many/Not enough arguments!" >&2; return -10; fi
 if ! [[ -f "$1" ]]; then echo "File doest't exist!" >&2; return -8; fi
-if ! [[ -f "$1" ]]; then echo "Can't read file!" >&2; return -9; fi
+if ! [[ -r "$1" ]]; then echo "Can't read file!" >&2; return -9; fi
 if [[ -f "$2" ]]; then
   if ! [[ -w "$2" ]]; then echo "Can't write in file!" >&2; return -11; fi
 fi
